"""empty message

Revision ID: 21efb182d7d2
Revises: 8b273ee6e697
Create Date: 2025-10-20 09:14:05.465963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21efb182d7d2'
down_revision = '8b273ee6e697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interacao', schema=None) as batch_op:
        batch_op.drop_column('curtida')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curtida', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('curtida')

    with op.batch_alter_table('interacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curtida', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
