"""empty message

Revision ID: d783f0130f91
Revises: 21efb182d7d2
Create Date: 2025-10-20 09:17:59.725924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd783f0130f91'
down_revision = '21efb182d7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('senha'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('senha'), ['senha'], unique=True)

    # ### end Alembic commands ###
